# Generated by Django 3.2.12 on 2022-03-20 11:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.shape')),
                ('shape', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            bases=('core.shape',),
        ),
        migrations.CreateModel(
            name='MultiPolygon',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.shape')),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            bases=('core.shape',),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.shape')),
                ('shape', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            bases=('core.shape',),
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('shape_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.shape')),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            bases=('core.shape',),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.layer')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='my_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.map'),
        ),
    ]
