version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build: 
    docker:
      - image: cimg/python:3.10.2
        environment:
          ENV: CIRCLE
          DATABASE_URL: postgresql://circleci@localhost/circle_test
      - image: cimg/postgres:12.10-postgis
        environment:
          PGHOST: localhost
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install libraries
          command: sudo apt-get update && sudo apt-get install binutils libproj-dev gdal-bin
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python manage.py test

workflows:
  build-and-test:
    jobs:
      - build
